version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: trae_user
      POSTGRES_PASSWORD: trae_password
      POSTGRES_DB: trae_nutrition
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/data:/docker-entrypoint-initdb.d:ro
    networks:
      - dokploy-network

  redis:
    image: redis:7-alpine
    networks:
      - dokploy-network

  backend:
    image: new-backend
    environment:
      PORT: 8080
      ENVIRONMENT: production
      DATABASE_URL: postgres://trae_user:trae_password@postgres:5432/trae_nutrition?sslmode=disable
      REDIS_URL: redis://redis:6379/0
      CORS_ALLOWED_ORIGINS: https://doctorhealthy1.com,https://reversproxy.doctorhealthy1.com
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
    depends_on:
      - postgres
      - redis
    networks:
      - dokploy-network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=dokploy-network"
        - "traefik.http.routers.backend.rule=Host(`backend.doctorhealth1.com`)"
        - "traefik.http.routers.backend.entrypoints=web"
        - "traefik.http.routers.backend.service=backend"
        - "traefik.http.services.backend.loadbalancer.server.port=8080"

  frontend:
    image: new-frontend
    environment:
      INTERNAL_API_URL: http://backend:8080/api
      NEXT_PUBLIC_API_URL: https://doctorhealthy1.com/api
      API_URL: http://46.62.228.173:8080/api
    depends_on:
      - backend
    networks:
      - dokploy-network

  nginx:
    image: nginx:alpine
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=dokploy-network"
        - "traefik.http.routers.app.rule=Host(`doctorhealthy1.com`)"
        - "traefik.http.routers.app.entrypoints=web"
        - "traefik.http.routers.app.service=app"
        - "traefik.http.services.app.loadbalancer.server.port=80"
        - "traefik.http.routers.reverse.rule=Host(`reversproxy.doctorhealthy1.com`)"
        - "traefik.http.routers.reverse.entrypoints=web"
        - "traefik.http.routers.reverse.service=reverse"
        - "traefik.http.services.reverse.loadbalancer.server.port=80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - dokploy-network

  ide-proxy:
    image: nginx:alpine
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=dokploy-network"
        - "traefik.http.routers.ide.rule=Host(`ide.doctorhealth1.com`)"
        - "traefik.http.routers.ide.entrypoints=web"
        - "traefik.http.routers.ide.service=ide"
        - "traefik.http.services.ide.loadbalancer.server.port=80"
    volumes:
      - ./nginx/ide.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - dokploy-network

volumes:
  postgres_data:

networks:
  dokploy-network:
    external: true
